from factory.Oracle_to_SQLserver import Oracle_to_SQLserver
from factory.SQLserver_to_SQLserver import SQLserver_to_SQLserver
from factory.Hive_to_SQLserver import Hive_to_SQLserver
from factory.Migrador import Migrador